print("Calcular el área se un Círculo")
print(" ")
pi=3.1416
r=float(input("Escribe el radio: "))
r_cuadrada=float(r*r)
print("Formula: 3.1416 X (r*r) ")
area_c=float(pi*r_cuadrada)
print(" ")
print("El área del círculo es: ", area_c)
print(" ")
print("Calcular el área se un Triángulo")
print(" ")
base_t=float(input("Escribe la base: "))
altura_t=float(input("Escribe la altura: "))
print("Formula: (B x H) / 2")
area_t=float((base_t*altura_t)/2)
print(" ")
print("El área del triángulo es: ", area_t)
print(" ")
print("Calcular el área se un Rectángulo")
print(" ")
base_r=float(input("Escribe la base: "))
altura_r=float(input("Escribe la altura: "))
print("Formula: B x H")
area_r=float(base_r*altura_r)
print(" ")
print("El área del Rectángulo es: ", area_r)
print(" ")