print ("Hola a Todos")
print(" ")
print("Tarea 1 Programación desde cero")
print(" ")
print("Presenta: Nayely")
print(" ")
print("Ada Lovelace es la primera programadora de la historia. ")
print("Tradujo y realizpo anotaciones detalladas de una memoria en francés sobre la Máquina Analítica escrita por Babbage ")
print(" ")
print("Programador favorito: John McAfee")
print(" ")
print("Escocia, 18 de septiembre de 1945")
print("Es un programador informático inglés y fundador de McAfee. Fue uno de los primeros en diseñar un software antivirus")
print("y de desarrollar un escáner de virus informático")
