print("Hola! \n Puedo calcular la sumatoria de dos núnmeros: ")
n1=float(input("Dame un número: "))
n2=float(input("Dame otro número: "))
r= float(n1 + n2)
print("El resultado de sumar ", n1, "y", n2,"es: ", r)